export enum SourceName {
  ALPHAVANTAGE = 'alphavantage',
  BINANCE = 'binance',
  BYBIT = 'bybit',
  COINBASE = 'coinbase',
  COINGECKO = 'coingecko',
  CRYPTOCOMPARE = 'cryptocompare',
  EXCHANGERATE_HOST = 'exchangerate-host',
  FINNHUB = 'finnhub',
  FRANKFURTER = 'frankfurter',
  KRAKEN = 'kraken',
  KUCOIN = 'kucoin',
  OKX = 'okx',
  YAHOO_FINANCE = 'yahoofinance',
}
